### ISSUE TITLE
MA difference calculation should be percentage based to account for scaling

### ISSUE THREAD

**Issue by LtheKid** [LtheKid/market_neutral#2]
Currently the MA strategy's calculation is based on MA short - MA long, where MA is the price value. This can result in scaling issues where the chosen stocks are those with larger magnitude but only because their prices are generally higher, thus making the differences higher.

Suggest to switch to a percentage based difference.

**Comment by clarayeooo** [comment]
Good point. Have updated the formula to compare the percentage change in MA(long/short) difference.:)
